services:
  inventario:
    build: .

    restart: unless-stopped

    ports:
      - "5000:5000"

    volumes:
      - inventario_data:/app/data
      - inventario_uploads:/app/static/uploads

volumes:
  inventario_data:
  inventario_uploads: